//Refer https://www.iban.com/country-codes
var teamNameAcronymn = {
    'Argentina': 'ARG',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Belgium': 'BEL',
    'Brazil': 'BRA',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Colombia': 'COL',
    'Costa Rica': 'CRC',
    'Croatia': 'CRO',
    'Czech Republic': 'CZE',
    'Denmark': 'DEN',
    'Egypt': 'EGY',
    'England': 'ENG',
    'Ecuador': 'ECU',
    'France': 'FRA',
    'Finland': 'FIN',
    'Ghana': 'GHA',
    'Germany': 'GER',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'Iran': 'IRN',
    'Italy': 'ITA',
    'Japan': 'JPN',
    'Korea Republic': 'KOR',
    'South Korea': 'KOR',
    'Mexico': 'MEX',
    'Morocco': 'MAR',
    'Nigeria': 'NGA',
    'Netherlands': 'NED',
    'North Macedonia': 'MKD',
    'Panama': 'PAN',
    'Peru': 'PER',
    'Poland': 'POL',
    'Portugal': 'POR',
    'Qatar': 'QAT',
    'Russia': 'RUS',
    'Saudi Arabia': 'KSA',
    'Scotland': 'SCO',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Slovakia': 'SVK',
    'Switzerland': 'SUI',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Uruguay': 'URU',
    'Ukraine': 'UKR',
    'Wales': 'WAL',
    'United States': 'USA',
    'TBD': 'TBD',
  }
  
  //Look at the folder /img/country-flags-main/* 
  //for the SVG name
  var teamFlag = {
    'Argentina': 'ar',
    'Australia': 'au',
    'Austria': 'at',
    'Belgium': 'be',
    'Brazil': 'br',
    'Cameroon': 'cr',
    'Canada': 'ca',
    'Colombia': 'co',
    'Costa Rica': 'cr',
    'Croatia': 'hr',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Ecuador': 'ec',
    'Egypt': 'eg',
    'England': 'gb',
    'France': 'fr',
    'Finland': 'fi',
    'Ghana': 'gh',
    'Germany': 'de',
    'Hungary': 'hu',
    'Iceland': 'is',
    'Iran': 'ir',
    'Italy': 'it',
    'Japan': 'jp',
    'Korea Republic': 'kp',
    'South Korea': 'kr',
    'Mexico': 'mx',
    'Morocco': 'ma',
    'Nigeria': 'ng',
    'Netherlands': 'nl',
    'North Macedonia': 'mk',
    'Panama': 'pa',
    'Peru': 'pe',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Qatar': 'qa',
    'Russia': 'ru',
    'Saudi Arabia': 'sa',
    'Scotland': 'gb-sct',
    'Senegal': 'sn',
    'Serbia': 'rs',
    'Spain': 'es',
    'Sweden': 'se',
    'Slovakia': 'sk',
    'Switzerland': 'ch',
    'Tunisia': 'tn',
    'Turkey': 'tr',
    'Uruguay': 'uy',
    'Ukraine': 'ua',
    'Wales': 'gb-wls',
    'United States': 'us',
  }